
<?php	
	session_start();		
	include_once("DataProvider.php");	
	if(isset($_REQUEST["btnDangNhap"])) 					   
	{		
		$UserName=$_REQUEST["txtTenDangNhap"];
		$PassWord=$_REQUEST["txtMatKhau"];		
		if(trim($UserName)=="")
		{
			$_SESSION['status']="chua_nhap_username";			
			exit;
		}
		else
		{
			if(trim($PassWord)=="")
			{
				$_SESSION['status']="chua_nhap_password";
				exit;
			}
			else
			{
				$User=DataProvider::ExecuteQuery("Select * from user where UserName='$UserName' ");
				$Row = mysql_fetch_array($User);
				if($Row!=null)
				{
					if($PassWord!=$Row["Pass"])
					{
						$_SESSION['status']="pass_word_khong_dung";
						exit;
					}
					else
					{
						$_SESSION["UserName"]=$Row["UserName"];
						$_SESSION["Pass"]=$Row["Pass"];
						$_SESSION["IsLogin"]=true;
						$_SESSION["UserType"]=$Row["UserStyleID"];
						$_SESSION['status']="login_successful";							
					}
				}				
				else
				{
						$_SESSION['status']="tai_khoan_chua_duoc_dang_ki";						
				}
			}
		}				
	}				
?>